### ISSUE TITLE
OPS: Create Shared Styles for Reusability Across Components

### ISSUE THREAD

**Issue by diverintech** [diverintech/diverintech.github.io#17]
## Objective
Create a centralized **`shared-styles`** folder to house general SCSS styles that can be imported into individual components. This will improve code reusability, maintainability, and ensure consistent styling across the application.

## Details
1. **Folder Structure**  
   Create a folder named `shared-styles` in the appropriate location (e.g., `src/styles/shared-styles`).

2. **Files to Add**  
   Add SCSS files to define the following reusable styles:

   - **_variables.scss**  
     Define global CSS variables such as:
     ```scss
     // Colors
     :root {
       --text-color-primary: #;
       --text-color-secondary: #;
       --text-color-alternative: #;
       --background-color-primary: #;
       --background-color-secondary: #;
     }

     // Font sizes
     --font-size-small: #;
     --font-size-medium: #;
     --font-size-large: #;

   - **_media-queries.scss**  
     Define reusable media query breakpoints:
     ```scss
     $screen-sm: 576px;
     $screen-md: 768px;
     $screen-lg: 992px;
     $screen-xl: 1200px;
     ```

---

## Tasks
- [ ] Create `shared-styles` folder
- [ ] Add the following SCSS files:
   - `_variables.scss` for global variables (colors, spacing, font-sizes).
   - `_media-queries.scss` for responsive breakpoints.
- [ ] Ensure styles can be imported into component-specific SCSS files.

---

## Expected Outcome
- A centralized `shared-styles` folder for managing reusable styles.
- Improved consistency across the app with easily accessible variables and mixins.
- Components can now import styles like:
   ```scss
   @use 'src/styles/shared-styles/variables' as *;
   @use 'src/styles/shared-styles/media-queries' as *;

   .example {
     color: var(--text-color-primary);
     @include respond-to(md) {
       font-size: var(--font-size-large);
     }
   }

**Comment by diverintech** [comment]
Começado por @fc46581 .

PR: https://github.com/diverintech/diverintech.github.io/pull/20
Branch: add-css-variables

**Comment by diverintech** [comment]
Example: https://css-tricks.com/approaches-media-queries-sass/
